services:

  simulator:
    image: mars-iot-simulator:multiarch_v1
    ports:
      - "8080:8080"
    networks:
      - mars-net
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/api/discovery')"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./templates/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./templates/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
      - "1883:1883"     # MQTT
    networks:
      - mars-net
    command: sh -c "rabbitmq-plugins enable --offline rabbitmq_mqtt && rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestion-service:
    build: ./sources/ingestion-service
    volumes:
      - ./templates/ingestion-service/config.yaml:/app/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy
      simulator:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - mars-net

networks:
  mars-net:
    driver: bridge